language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build primary_connect_client.gemspec
  - gem install ./primary_connect_client-1.0.1.gem
