=begin
#API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for PrimaryConnectClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = PrimaryConnectClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(PrimaryConnectClient::DefaultApi)
    end
  end

  # unit tests for api_v1_events_get
  # list events
  # @param [Hash] opts the optional parameters
  # @option opts [String] :last_event_id 
  # @option opts [String] :event_types 
  # @return [nil]
  describe 'api_v1_events_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_messages_get
  # list messages
  # @param [Hash] opts the optional parameters
  # @return [Array<Message>]
  describe 'api_v1_messages_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_orders_get
  # list orders
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_orders_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_orders_id_get
  # show order
  # @param id id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_orders_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_orders_order_id_results_get
  # list results
  # @param order_id Order id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_orders_order_id_results_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_orders_order_id_results_id_get
  # show result
  # @param order_id Order id
  # @param id id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_orders_order_id_results_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_orders_post
  # create order
  # @param [Hash] opts the optional parameters
  # @option opts [Order] :order 
  # @return [nil]
  describe 'api_v1_orders_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
