=begin
#Primary Connect API V1

#Client Library to interface with Primary Connect

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PrimaryConnectClient::OrderOrderDiagnoses
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PrimaryConnectClient::OrderOrderDiagnoses do
  let(:instance) { PrimaryConnectClient::OrderOrderDiagnoses.new }

  describe 'test an instance of OrderOrderDiagnoses' do
    it 'should create an instance of OrderOrderDiagnoses' do
      expect(instance).to be_instance_of(PrimaryConnectClient::OrderOrderDiagnoses)
    end
  end
  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["TYPE_UNKNOWN", "TYPE_ADMITTING", "TYPE_FINAL", "TYPE_SELF", "TYPE_WORKING", "TYPE_PRINCIPAL"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "documented_date_time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
