=begin
#Primary Connect API V1

#Client Library to interface with Primary Connect

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PrimaryConnectClient::VisitGuarantorEmployer
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PrimaryConnectClient::VisitGuarantorEmployer do
  let(:instance) { PrimaryConnectClient::VisitGuarantorEmployer.new }

  describe 'test an instance of VisitGuarantorEmployer' do
    it 'should create an instance of VisitGuarantorEmployer' do
      expect(instance).to be_instance_of(PrimaryConnectClient::VisitGuarantorEmployer)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "phone_numbers"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "address"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
