=begin
#Primary Connect API V1

#Client Library to interface with Primary Connect

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1-SNAPSHOT

=end

# Common files
require 'primary_connect_client/api_client'
require 'primary_connect_client/api_error'
require 'primary_connect_client/version'
require 'primary_connect_client/configuration'

# Models
require 'primary_connect_client/models/address'
require 'primary_connect_client/models/identifier'
require 'primary_connect_client/models/location'
require 'primary_connect_client/models/message'
require 'primary_connect_client/models/message_destination'
require 'primary_connect_client/models/name'
require 'primary_connect_client/models/order'
require 'primary_connect_client/models/order_clinical_info'
require 'primary_connect_client/models/order_diagnoses'
require 'primary_connect_client/models/order_ordering_facility'
require 'primary_connect_client/models/order_procedure'
require 'primary_connect_client/models/order_specimen'
require 'primary_connect_client/models/patient'
require 'primary_connect_client/models/patient_contacts'
require 'primary_connect_client/models/patient_demographics'
require 'primary_connect_client/models/phone_number'
require 'primary_connect_client/models/provider'
require 'primary_connect_client/models/visit'
require 'primary_connect_client/models/visit_company'
require 'primary_connect_client/models/visit_guarantor'
require 'primary_connect_client/models/visit_guarantor_employer'
require 'primary_connect_client/models/visit_insurances'
require 'primary_connect_client/models/visit_insured'
require 'primary_connect_client/models/visit_plan'

# APIs
require 'primary_connect_client/api/default_api'

module PrimaryConnectClient
  class << self
    # Customize default settings for the SDK using block.
    #   PrimaryConnectClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
